version: "3.9"

services:

  BNPos:
    image: postgres:latest
    container_name: OneTest
    environment:
      POSTGRES_USER: BN
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5420:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - PostgresBN


networks:
  PostgresBN:
    driver: bridge

volumes:
  pg_data: